# Generated by Django 4.2.9 on 2024-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='valuation',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
