# Generated by Django 5.0.1 on 2024-01-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('editora', models.CharField(max_length=30)),
                ('ano_publicacao', models.IntegerField(default=0)),
                ('qntd_paginas', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0.0)),
            ],
        ),
    ]
