# Generated by Django 5.0.1 on 2024-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acougue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_carne', models.CharField(max_length=30)),
                ('tipo_carne', models.CharField(max_length=30)),
                ('fazenda', models.CharField(max_length=30)),
                ('data_corte', models.IntegerField(default=0)),
                ('preco_carne', models.FloatField(default=0.0)),
            ],
        ),
    ]
