# Generated by Django 5.0.1 on 2024-01-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeuSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('profissao', models.CharField(max_length=30)),
                ('estuda', models.CharField(max_length=60)),
                ('busca', models.TextField(max_length=350)),
            ],
        ),
    ]
