# Generated by Django 5.0.1 on 2024-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('especie', models.CharField(max_length=30)),
                ('caracteristicas', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('reino', models.CharField(max_length=30)),
            ],
        ),
    ]
