# Generated by Django 4.2.9 on 2024-01-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farmacias')),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cad_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
