# Generated by Django 5.0.1 on 2024-01-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroInss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('idade', models.IntegerField(default=0)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('data_cadastro', models.DateField()),
            ],
        ),
    ]
