# Generated by Django 4.2.9 on 2024-01-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=150)),
                ('idade', models.IntegerField(default=0)),
                ('cpf', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('dia_consulta', models.CharField(choices=[('DOM', 'Domingo'), ('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sabado')], default='DOM', max_length=3)),
                ('imagem', models.ImageField(upload_to='fotos')),
                ('hora_marcada', models.DateField(auto_now_add=True)),
                ('processo_agendado', models.TextField()),
            ],
        ),
    ]
