# Generated by Django 5.0.1 on 2024-01-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=30)),
                ('pintura', models.CharField(max_length=30)),
                ('ano', models.IntegerField(default=0)),
                ('placa', models.CharField(max_length=30)),
            ],
        ),
    ]
